### ISSUE TITLE
unmount Listener error

### ISSUE THREAD

**Issue by alexlipe** [evetstech/react-native-animated-ptr#5]
RN 0.31. IOS and Andorid
page1 set prt
page2 set prt

page1 -> push -> page2 -> pop ->page1  then,show error:

undefined is not an object(evaluating 'this._listeners[id].x')

removeListener
AnimatedImplementation.js:897

componentWillUnmout
ScrollAnimationjs:116

**Comment by evetstech** [comment]
Thanks for submitting this issue, and sorry for not looking into it earlier.  It is fixed now with commit 7b6e16ae9fc101cab9b91ad3eb4f7b667b849200
