### ISSUE TITLE
ListView onEndReached error

### ISSUE THREAD

**Issue by alexlipe** [evetstech/react-native-animated-ptr#6]
if contentComponent use ListView , and set ListView onEndReached .   will auto run onEndReached.

**Comment by evetstech** [comment]
This is a react-native thing, more so than the component.  To test this, you make just a ListView with said callback, and it'll still trigger before anything is reached.  If you set onEndReachedThreshold in the ListView as well, you could have it not be called (I set it to 0, and it had to be scrolled to the bottom before it was called, for example).
